// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovykodbndubkylfdjxnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92eWtvZGJuZHVia3lsZmRqeG50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjQ0MzYsImV4cCI6MjA2NzY0MDQzNn0.Z1qwXWZlKeKDhR5wFHm2Ki4TYzWAyqt6FsSrCqxRIwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});